version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: openfga
      POSTGRES_USER: openfga
      POSTGRES_PASSWORD: openfga
    ports:
      - "5432:5432"
    volumes:
      - openfga-db-data:/var/lib/postgresql/data
  openfga-migrate:
    image: openfga/openfga:v1.5.5
    depends_on:
      - db
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@db:5432/openfga?sslmode=disable
    command: ["migrate"]
  openfga:
    image: openfga/openfga:v1.5.5
    depends_on:
      - db
      - openfga-migrate
    ports:
      - "8080:8080"
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@db:5432/openfga?sslmode=disable
    command: ["run"]
volumes:
  openfga-db-data:
